name: auto-release
on:
  push:
    branches:
      - main
    paths:
      - event.json
      - icon.json
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v1
        with:
          ref: 'main'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: enable problem matcher
        run: |
          echo "::add-matcher::.github/problem-matcher.json"
      - name: run test
        run: |
          gem install minitest
          ruby test.rb
      - name: update release
        run: |
          ruby release.rb
      - name: commit and push
        env:
          REPO: https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
        run: |
          git config --global user.email "s.kaoru509@gmail.com"
          git config --global user.name "Seo-4d696b75"
          git add .
          git commit -m '[update] release'
          git push ${REPO} main
