name: auto-update-schedule
on:
  schedule:
    - cron: '0 15 * * *' # JST+0900 で毎時0:00に実行
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v1
        with:
          ref: 'main'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: update
        run: ruby update.rb
      - name: check diff
        id: diff
        run: |
          git add -N . # 新規ファイルを含める
          echo "::set-output name=count::$(git diff --name-only | wc -l)"
      - name: release
        if: steps.diff.outputs.count > 0
        run: ruby release.rb
      - name: commit and push
        if: steps.diff.outputs.count > 0
        env:
          REPO: https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
        run: |
          git config --global user.email "s.kaoru509@gmail.com"
          git config --global user.name "Seo-4d696b75"
          git add .
          git commit -m '[update] release'
          git push ${REPO} main
